---
- name: Install Nginx
  ansible.builtin.dnf:
    state: present
    name: nginx

- name: Create sites-available folder
  ansible.builtin.file:
    path: /etc/nginx/sites-available
    state: directory
    mode: '0755'

- name: Create sites-enabled folder
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled
    state: directory
    mode: '0755'

- name: Create SSL folder to store certificates
  ansible.builtin.file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0755'

- name: Copy Nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable autostart and run Nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: started
