# vim:ft=yaml.ansible:
---

  - name: Add the epel repository
    yum:
      state: present
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

  - name: Install additional software for work
    yum:
      state: present
      name:
        - emacs
        - the_silver_searcher
    notify:
      - Update locate DB

  - name: Copy handy scripts
    copy:
      src: "{{item}}"
      dest: /root/work/bin
      owner: root
      mode: 0644
    with_fileglob:
      - ~/work/src/github.com/alkurbatov/dotfiles/bin/reset-hci-logs

  - name: Increase nginx logs verbosity
    replace:
      path: /etc/nginx/nginx.conf
      regexp: 'error_log /var/log/nginx/error.log;'
      replace: 'error_log /var/log/nginx/error.log warn;'
      backup: no
    notify:
      -  Restart nginx

# FIXME (alkurbatov): Use templates to somehow reduce the code duplication.
  - name: Allow anonymous access to Agent
    replace:
      path: /etc/nginx/conf.d/vstorage-ui-agent.conf
      regexp: "ssl_verify_client on"
      replace: "ssl_verify_client off"
      backup: no
    when: agent_access == "external"
    notify:
      -  Restart nginx

  - name: Disable anonymous access to Agent
    replace:
      path: /etc/nginx/conf.d/vstorage-ui-agent.conf
      regexp: "ssl_verify_client off"
      replace: "ssl_verify_client on"
      backup: no
    when: agent_access == "local"
    notify:
      -  Restart nginx

  - name: Generate OpenStack credentials
    command: kolla-ansible post-deploy
    become: yes
    become_user: vstoradmin
    register: cred_gen_result
    changed_when: cred_gen_result.stdout is search('changed=1')
    when: role_in_cluster == "controller"

  - name: Disable the Shaman daemon
    systemd:
      name: shaman@{{ cluster_name }}
      state: stopped
      masked: yes

  - name: Set cluster's replicas to 3
    command: "vstorage -c {{ cluster_name }} set-attr -R -p / replicas=3"
    when: role_in_cluster == "controller"

# FIXME (alkurbatov): I doubt that we can do it more then once.
  - name: Create very small OpenStack flavor
    shell: source /etc/kolla/admin-openrc.sh && openstack --insecure flavor create --ram 64 --disk 1 super-tini
    when: role_in_cluster == "controller"

  - name: Extend keystone token lifetime
    ini_file:
      dest: /usr/libexec/vstorage-ui-backend/etc/keystone/keystone.conf
      section: token
      option: expiration
      value: "360000"
    when: role_in_cluster == "controller"
    notify:
      - Restart keystone-admin
      - Restart vstorage-ui-keystone-public

  - name: Enable tracebacks in Backend responces
    replace:
      path: /usr/libexec/vstorage-ui-backend/etc/backend.cfg
      regexp: '(TRACE_MESSAGES =) False'
      replace: '\1 True'
      backup: no
    when: role_in_cluster == "controller"
    notify:
      -  Restart vstorage-ui-backend

  - name: Create a viewer user
    shell: echo {{ admin_password }} | vinfra --vinfra-password {{ admin_password }} domain user create Viewer --domain default --system-permissions viewer
    when: role_in_cluster == "controller"
