---
- name: Deploy ML working environment
  hosts: mldev
  become: true
  vars:
    developer: '{{ ansible_user }}'
    developer_home: '/home/{{ developer }}'
    github_sources_folder: '{{ developer_home }}/work/src/github.com'
    developer_sources_folder: '{{ github_sources_folder }}/{{ developer }}'
  tasks:
    - name: Update the system
      ansible.builtin.include_role:
        name: devserver
        tasks_from: update-packages

    - name: Configure swap
      ansible.builtin.include_role:
        name: devserver
        tasks_from: configure-swap

    - name: Disable IPv6
      ansible.builtin.include_role:
        name: devserver
        tasks_from: disable-ipv6

    - name: Setup developer environment
      ansible.builtin.include_role:
        name: devenv
        tasks_from: setup

    - name: Configure zsh
      ansible.builtin.include_role:
        name: devenv
        tasks_from: reconfigure-zsh

    - name: Configure MC
      ansible.builtin.include_role:
        name: devenv
        tasks_from: reconfigure-mc

    - name: Setup Emacs
      ansible.builtin.include_role:
        name: emacs
        tasks_from: setup

    - name: Setup Nginx
      ansible.builtin.include_role:
        name: nginx
        tasks_from: setup

    - name: Setup Jupyter
      ansible.builtin.include_role:
        name: jupyter
        tasks_from: setup
