# vim:ft=yaml.ansible:
---

  - name: Install additional software for work
    dnf:
      state: present
      name: [
        'ant',
        'java-11-openjdk',
        'ruby'
      ]

  - name: Download Sencha installer
    get_url:
      url: http://cdn.sencha.com/cmd/6.7.0.63/no-jre/SenchaCmd-6.7.0.63-linux-amd64.sh.zip
      dest: /root/work/tmp
      mode: '0440'

  - name: Extract Sencha installer into /root/work/tmp
    unarchive:
      src: /root/work/tmp/SenchaCmd-6.7.0.63-linux-amd64.sh.zip
      dest: /root/work/tmp
      remote_src: yes

  - name: Install Sencha
    command: /root/work/tmp/SenchaCmd-6.7.0.63-linux-amd64.sh -Dall=true -q -dir /opt/Sencha/Cmd/

  - name: Open 3.5 admin panel port
    firewalld:
      port: 8888/tcp
      permanent: yes
      state: enabled
      immediate: yes

  - name: Open HCI admin panel port (launched from source code)
    firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled
      immediate: yes

  - name: Open extjs admin panel port
    firewalld:
      port: 7000/tcp
      permanent: yes
      state: enabled
      immediate: yes

  - name: Copy application configs
    copy:
      src: extjsdev.setup/files/nginx/sites-available
      dest: /etc/nginx/
    notify:
      - Restart nginx

  - name: Enable 3.5 application config
    file:
      src: /etc/nginx/sites-available/pstorage-ui.conf
      dest: /etc/nginx/sites-enabled/pstorage-ui.conf
      owner: root
      group: root
      state: link
    notify:
      - Restart nginx

  - name: Enable 4.0+ application config
    file:
      src: /etc/nginx/sites-available/pstorage-ui-new.conf
      dest: /etc/nginx/sites-enabled/pstorage-ui-new.conf
      owner: root
      group: root
      state: link
    notify:
      - Restart nginx
