# vim:ft=yaml.ansible:
---

  - name: Install additional software for work
    dnf:
      state: present
      name: [
        ant,
        java-11-openjdk,
        ruby,
        tar,
        unzip,
      ]

  - name: Download Sencha installer
    get_url:
      url: http://cdn.sencha.com/cmd/6.7.0.63/no-jre/SenchaCmd-6.7.0.63-linux-amd64.sh.zip
      dest: /root/work/tmp
      mode: '0440'

  - name: Extract Sencha installer into /root/work/tmp
    unarchive:
      src: /root/work/tmp/SenchaCmd-6.7.0.63-linux-amd64.sh.zip
      dest: /root/work/tmp
      remote_src: yes

  - name: Install Sencha
    command: /root/work/tmp/SenchaCmd-6.7.0.63-linux-amd64.sh -Dall=true -q -dir /opt/Sencha/Cmd/

  - name: Open the Admin panel access port
    firewalld:
      port: 8888/tcp
      permanent: yes
      state: enabled
      immediate: yes

  - name: Open the Self-service panel access port
    firewalld:
      port: 8800/tcp
      permanent: yes
      state: enabled
      immediate: yes

  - name: Open the coverage report access port
    firewalld:
      port: 7000/tcp
      permanent: yes
      state: enabled
      immediate: yes

  - name: Copy application configs
    copy:
      src: uidev.setup/files/nginx/sites-available
      dest: /etc/nginx/

  - name: Enable the Admin panel config
    file:
      src: /etc/nginx/sites-available/admin-panel.conf
      dest: /etc/nginx/sites-enabled/admin-panel.conf
      owner: root
      group: root
      state: link

  - name: Enable the Self-service panel config
    file:
      src: /etc/nginx/sites-available/self-service-panel.conf
      dest: /etc/nginx/sites-enabled/self-service-panel.conf
      owner: root
      group: root
      state: link

  - name: Enable the coverage config
    file:
      src: /etc/nginx/sites-available/coverage.conf
      dest: /etc/nginx/sites-enabled/coverage.conf
      owner: root
      group: root
      state: link

  - name: Make root folder accessible to Nginx
    file:
      path: /root
      state: directory
      mode: '0551'

  - name: Increase max watchers limit to be able to launch both panels in dev mode
    sysctl:
      name: fs.inotify.max_user_watches
      value: '524288'
      state: present
