# vim:ft=yaml.ansible:
---

  - name: Install vim colorschemes
    git:
      repo: https://github.com/flazz/vim-colorschemes.git
      dest: /root/.local/share/nvim/site/pack/core/start/vim-colorschemes
      version: HEAD
    tags:
      - skip_ansible_lint

  - name: Install ale vim plugin
    git:
      repo: https://github.com/dense-analysis/ale.git
      dest: /root/.local/share/nvim/site/pack/linting/opt/ale
      depth: 1
      version: v2.6.0

  - name: Install vim-vue-plugin
    git:
      repo: https://github.com/leafOfTree/vim-vue-plugin.git
      dest: /root/.local/share/nvim/site/pack/js/opt/vim-vue-plugin
      version: v1.0.20191126

  - name: Install git-messenger vim plugin
    git:
      repo: https://github.com/rhysd/git-messenger.vim.git
      dest: /root/.local/share/nvim/site/pack/git/start/git-messenger
      version: HEAD
    tags:
      - skip_ansible_lint

  - name: Install python-syntax vim plugin
    git:
      repo: https://github.com/vim-python/python-syntax.git
      dest: /root/.local/share/nvim/site/pack/python/opt/python-syntax
      version: HEAD
    tags:
      - skip_ansible_lint

  - name: Install nginx vim plugin
    git:
      repo: https://github.com/chr4/nginx.vim.git
      dest: /root/.local/share/nvim/site/pack/web/opt/nginx.vim
      version: HEAD
    tags:
      - skip_ansible_lint

  - name: Install fzf plugin
    git:
      repo: https://github.com/junegunn/fzf.git
      dest: /root/.local/share/nvim/site/pack/core/start/fzf
      version: HEAD
    tags:
      - skip_ansible_lint

  - name: Install fzf.vim plugin
    git:
      repo: https://github.com/junegunn/fzf.vim.git
      dest: /root/.local/share/nvim/site/pack/core/start/fzf.vim
      version: HEAD
    tags:
      - skip_ansible_lint

  - name: Install vim-gitgutter plugin
    git:
      repo: https://github.com/airblade/vim-gitgutter.git
      dest: /root/.local/share/nvim/site/pack/git/start/vim-gitgutter
      version: HEAD
    tags:
      - skip_ansible_lint

  - name: Install NERD tree plugin
    git:
      repo: https://github.com/preservim/nerdtree.git
      dest: /root/.local/share/nvim/site/pack/core/start/nerdtree
      version: 6.9.0

  - name: Install ansible-vim plugin
    git:
      repo: https://github.com/pearofducks/ansible-vim.git
      dest: /root/.local/share/nvim/site/pack/ansible/opt/ansible-vim
      version: 2.2

  - name: Copy neovim configs
    copy:
      src: ~/work/src/github.com/alkurbatov/dotfiles/.config/nvim
      dest: /root/.config/
