---
- name: Download Spark from upstream
  ansible.builtin.git:
    repo: git@github.com:apache/spark.git
    dest: '{{ github_sources_folder }}/apache/spark'
  become_user: '{{ developer }}'

- name: Download SynapseML from upstream
  ansible.builtin.git:
    repo: git@github.com:microsoft/SynapseML.git
    dest: '{{ github_sources_folder }}/microsoft/synapseml'
  become_user: '{{ developer }}'

- name: Download MLflow from upstream
  ansible.builtin.git:
    repo: git@github.com:mlflow/mlflow.git
    dest: '{{ github_sources_folder }}/mlflow/mlflow'
  become_user: '{{ developer }}'
