---
- name: Create .gnupg folder
  ansible.builtin.file:
    path: '{{ developer_home }}/.gnupg'
    state: directory
    owner: '{{ developer }}'
    group: '{{ developer }}'
    mode: '0700'

- name: Copy GPG config to be able to sign commits inside virtual machines
  ansible.builtin.copy:
    src: gpg.conf
    dest: '{{ developer_home }}/.gnupg/'
    owner: '{{ developer }}'
    group: '{{ developer }}'
    mode: '0600'

- name: Copy signing GPG key
  ansible.builtin.copy:
    src: '~/work/etc/{{ developer_gpg_key }}.key'
    dest: '{{ developer_home }}/work/etc/'
    owner: '{{ developer }}'
    group: '{{ developer }}'
    mode: '0600'
  notify:
    - Import GPG key
    - Trust to GPG key
