---
- name: Install additional software
  ansible.builtin.dnf:
    state: present
    name: [
      ShellCheck,
      bat,
      curl,
      git,
      gpgme,
      htop,
      jetbrains-mono-fonts-all,
      jq,
      langpacks-ru,
      lsof,
      make,
      mc,
      nodejs,
      npm,
      patch,
      poetry,
      rpmconf,
      rsync,
      screen,
      strace,
      tar,
      telnet,
      the_silver_searcher,
      tmux,
      unzip,
      util-linux-user,
      wget,
      zip,
      zsh,
    ]

- name: Install pyright
  community.general.npm:
    name: pyright
    global: true

- name: Make ZSH the default shell
  ansible.builtin.user:
    name: '{{ developer }}'
    shell: /usr/bin/zsh

- name: Create the work folders
  ansible.builtin.file:
    path: '{{ developer_home }}/work/{{ item }}'
    state: directory
    owner: '{{ developer }}'
    group: '{{ developer }}'
    mode: '0700'
  loop:
    - bin
    - etc
    - pkg
    - src/github.com/alkurbatov
    - tmp

- name: Copy SSH keys
  ansible.builtin.copy:
    src: '~/.ssh/{{ item }}'
    dest: '{{ developer_home }}/.ssh/'
    owner: '{{ developer }}'
    group: '{{ developer }}'
    mode: '0600'
  loop:
    - github

- name: Copy SSH config
  ansible.builtin.copy:
    src: ssh/config
    dest: '{{ developer_home }}/.ssh/'
    owner: '{{ developer }}'
    group: '{{ developer }}'
    mode: '0600'

- name: Download dotfiles
  ansible.builtin.git:
    repo: git@github.com:alkurbatov/dotfiles.git
    dest: '{{ developer_sources_folder }}/dotfiles'
    accept_hostkey: true
  become_user: '{{ developer }}'
  notify:
    - Install dotfiles

- name: Copy top utility config
  ansible.builtin.copy:
    src: toprc
    dest: '{{ developer_home }}/.config/procps/'
    owner: '{{ developer }}'
    group: '{{ developer }}'
    mode: '0644'
