# vim:ft=yaml.ansible:
---

  - name: Install additional software for work
    yum:
      state: present
      name: [
        ShellCheck,
        neovim,
        python36-pylint,
        the_silver_searcher,
      ]

  - name: Copy Backend test config
    copy:
      src: backend-dev.setup/files/test.cfg
      dest: /root/work/etc/
      owner: root
      mode: '0600'

  - name: Create a work/src folder
    file:
      path: /root/work/src/git.acronis.com/alkurbatov
      state: directory
      mode: '0755'

  - name: Copy developer key
    copy:
      src: ~/.ssh/acronis_rsa
      dest: /root/.ssh
      owner: root
      mode: '0600'

  - name: Copy ssh config
    copy:
      src: backend-dev.setup/files/config
      dest: /root/.ssh
      owner: root
      mode: '0600'

  - name: Copy bash config
    copy:
      src: backend-dev.setup/files/.bashrc
      dest: /root/
      owner: root
      mode: '0600'

  - name: Copy .inputrc
    copy:
      src: ~/work/src/github.com/alkurbatov/dotfiles/.inputrc
      dest: /root/
      owner: root
      mode: '0600'

  - name: Copy git config
    copy:
      src: ~/work/src/github.com/alkurbatov/dotfiles/git/.gitconfig
      dest: /root
      owner: root
      mode: '0600'

  - name: Copy global gitignore
    copy:
      src: ~/work/src/github.com/alkurbatov/dotfiles/git/.gitignore
      dest: /root
      owner: root
      mode: '0600'

  - name: Create a .gnupg folder
    file:
      path: ~/.gnupg
      state: directory
