# vim:ft=yaml.ansible:
---
  - name: Disable hci-base release repo
    ini_file:
      dest: /etc/yum.repos.d/hci.repo
      section: hci-base
      option: enabled
      value: '0'
      backup: no

  - name: Disable hci-updates release repo
    ini_file:
      dest: /etc/yum.repos.d/hci.repo
      section: hci-updates
      option: enabled
      value: '0'
      backup: no

  - name: Activate hci-devel repo
    ini_file:
      dest: /etc/yum.repos.d/hci-devel.repo
      section: hci-devel
      option: enabled
      value: '1'
      backup: no

  - name: Disable the readykernel repository
    ini_file:
      path: /etc/yum.repos.d/readykernel.repo
      section: readykernel
      option: enabled
      value: "0"
      backup: no

  - name: Disable readykernel autoupdates
    command: readykernel autoupdate disable

  - name: Add the aux repository
    yum_repository:
      file: aux
      name: aux
      description: UI testing repository
      baseurl: http://kojistorage.builder.corp.acronis.com/mash/hci-{{release}}-{{brand}}/latest/x86_64/os/
      priority: "100"
      gpgcheck: no

  - name: Create a work/etc folder
    file:
      path: /root/work/etc
      state: directory
      mode: '0755'

  - name: Create the work folder
    file:
      path: /root/work/bin
      state: directory

  - name: Install basic software for work
    yum:
      state: present
      name:
        - curl
        - gdb
        - htop
        - iotop
        - iproute
        - lsof
        - mc
        - mlocate
        - rh-python36-python-debug
        - screen
        - strace
        - yum-utils
        - wget
    notify:
      - Update locate DB
