# vim:ft=yaml.ansible:
---

  - name: Install additional software for work
    dnf:
      state: present
      name: [
        docker,
        docker-compose,
        grubby,
        pass,
      ]

  - name: Apply workaround to make docker work with new cgroups
    command: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
    notify:
      - Reboot node

  - name: Identify backend used by firewalld
    command: /usr/bin/grep -oP 'FirewallBackend=\K\w+' /etc/firewalld/firewalld.conf
    register: firewalld_driver

  - debug:
      msg: "Firewalld uses the {{ firewalld_driver.stdout }} driver"

  - name: Apply workaround to make docker work with firewalld
    lineinfile:
      path: /etc/firewalld/firewalld.conf
      regexp: '^FirewallBackend='
      line: FirewallBackend=iptables
    when: firewalld_driver.stdout == "nftables"
    notify:
      - Restart firewalld
      - Restart docker

  - name: Create a tmp folder
    file:
      path: /root/work/tmp
      state: directory
      mode: '0755'

  - name: Download docker-credential-pass
    get_url:
      url: https://github.com/docker/docker-credential-helpers/releases/download/v0.6.3/docker-credential-pass-v0.6.3-amd64.tar.gz
      dest: /root/work/tmp
      mode: '0440'

  - name: Install docker-credential-pass
    unarchive:
      src: /root/work/tmp/docker-credential-pass-v0.6.3-amd64.tar.gz
      dest: /usr/local/bin
      mode: '0755'
      remote_src: yes

  - name: Create docker config folder
    file:
      path: ~/.docker
      state: directory
      mode: '0700'

  - name: Copy docker config
    copy:
      src: docker.setup/files/docker.json
      dest: /root/.docker/config.json
      owner: root
      mode: '0600'

  - name: Initialize password store
    command: /usr/bin/pass init alkurbatov@umbrella.org
    args:
      creates: /root/.password-store

  - name: Enable autostart of the docker service
    systemd:
      name: docker
      enabled: yes
