---
- name: Install Emacs and dependencies
  ansible.builtin.dnf:
    state: present
    name: [
      pandoc,
      emacs,
      multimarkdown,
    ]

- name: Download Emacs configs
  ansible.builtin.git:
    repo: git@github.com:alkurbatov/nano-emacs.git
    dest: '{{ developer_sources_folder }}/nano-emacs'
  become_user: '{{ developer }}'
  notify:
    - Install Emacs configuration
