---

  - name: Install additional software from Fedora repos
    dnf:
      state: present
      name: [
        java-1.8.0-openjdk, # for Spark 2.4.5
        python3.7,
      ]

  - name: Open ports required to interact with remote Spark
    firewalld:
      port: "{{ item }}/tcp"
      permanent: yes
      state: enabled
      immediate: yes
    loop:
      - 39113 # block manager port
      - 45931 # driver port
