# vim:ft=yaml.ansible:
---

  - name: Check if epel repo file exists
    stat:
      path: /etc/yum.repos.d/epel.repo
    register: epel_repo_exists

  - name: Disable epel repo
    ini_file:
      dest: /etc/yum.repos.d/epel.repo
      section: epel
      option: enabled
      value: '0'
      backup: no
    when: epel_repo_exists.stat.exists == true

  - name: Update all packages
    yum:
      name: "*"
      state: latest
      update_cache: yes
    notify:
      - Update locate DB
      - Reboot node

  - name: Update docker containers
    command: kolla-ansible upgrade
    become: yes
    become_user: vstoradmin
    when: role_in_cluster == "controller"
