# vim:ft=yaml.ansible:
---

  - name: Check if epel repo file exists
    stat:
      path: /etc/yum.repos.d/epel.repo
    register: epel_repo_exists

  - name: Disable epel repo
    ini_file:
      dest: /etc/yum.repos.d/epel.repo
      section: epel
      option: enabled
      value: '0'
      backup: no
    when: epel_repo_exists.stat.exists == true

  # FIXME (alkurbatov): Remove when update will work with the enabled hci-devel.
  - name: Disable hci-devel repo
    ini_file:
      dest: /etc/yum.repos.d/hci-devel.repo
      section: hci-devel
      option: enabled
      value: '0'
      backup: no

  - name: Update all packages
    yum:
      name: "*"
      state: latest
      update_cache: yes
    notify:
      - Update locate DB
      - Reboot node

  - name: Determine whether docker containers exists
    shell: /usr/bin/docker ps -a --quiet | /usr/bin/wc -l
    register: docker_containers_count
    changed_when: false

  - name: Update docker containers
    command: kolla-ansible upgrade
    become: yes
    become_user: vstoradmin
    when: role_in_cluster == 'controller' and docker_containers_count.stdout != '0'
