# vim:ft=yaml.ansible:
---

  - name: Check if epel repo file exists
    stat:
      path: /etc/yum.repos.d/epel.repo
    register: epel_repo_exists

  - name: Disable epel repo
    ini_file:
      dest: /etc/yum.repos.d/epel.repo
      section: epel
      option: enabled
      value: '0'
      backup: no
    when: epel_repo_exists.stat.exists == true

  # FIXME (alkurbatov): Remove when update will work with the enabled hci-devel.
  - name: Disable hci-devel repo
    ini_file:
      dest: /etc/yum.repos.d/hci-devel.repo
      section: hci-devel
      option: enabled
      value: '0'
      backup: no

  - name: Update all packages
    yum:
      name: "*"
      state: latest
      update_cache: yes
    notify:
      - Update locate DB
      - Reboot node

  - name: Remove old compute tarballs
    shell: /bin/rm -f /usr/share/hci-docker/*
    args:
      warn: false
    when: role_in_cluster == 'controller'

  - name: Get kolla-ansible package version
    command: rpm -q --queryformat '%{VERSION}-%{RELEASE}' kolla-ansible
    args:
      warn: false
    register: kolla_package_version
    changed_when: false
    when: role_in_cluster == 'controller'

  - name: Download kolla tarball
    get_url:
      url: https://kojistorage.builder.corp.acronis.com/hci-docker-images/hci-docker-images-{{ kolla_package_version.stdout }}.tar.gz
      dest: /usr/share/hci-docker/
      mode: '0444'
    when: role_in_cluster == 'controller'

  - name: Download kolla filelist
    get_url:
      url: https://kojistorage.builder.corp.acronis.com/hci-docker-images/hci-docker-images-{{ kolla_package_version.stdout }}.filelist
      dest: /usr/share/hci-docker/
      mode: '0444'
    when: role_in_cluster == 'controller'

  - name: Determine whether docker containers exists
    shell: /usr/bin/docker ps -a --quiet | /usr/bin/wc -l
    register: docker_containers_count
    changed_when: false
    when: role_in_cluster == 'controller'

  - name: Unpack kolla tarball
    unarchive:
      src: /usr/share/hci-docker/hci-docker-images-{{ kolla_package_version.stdout }}.tar.gz
      dest: /var/lib/registry/
      remote_src: yes
    when: role_in_cluster == 'controller' and docker_containers_count.stdout != '0'

  - name: Update docker containers
    command: kolla-ansible upgrade
    become: yes
    become_user: vstoradmin
    when: role_in_cluster == 'controller' and docker_containers_count.stdout != '0'
