---

  - name: Install additional software
    yum:
      state: present
      name: [
        ShellCheck,
        aspell,
        aspell-en,
        aspell-ru,
        black,
        emacs,
        fd-find,
        multimarkdown,
        python3-autopep8,
        python3-virtualenvwrapper,
        the_silver_searcher,
      ]

  - name: Create Emacs config folder
    file:
      path: /root/.emacs.d
      state: directory
      mode: '0755'

  - name: Copy Emacs configs
    copy:
      src: "~/work/src/github.com/alkurbatov/emacs.d/{{item}}"
      dest: /root/.emacs.d/
      owner: root
      mode: '0644'
    loop:
      - early-init.el
      - init.el
      - lisp
      - snippets
