---
- name: Install password manager
  ansible.builtin.dnf:
    state: present
    name: pass

- name: Download docker-credential-pass
  ansible.builtin.get_url:
    url: https://github.com/docker/docker-credential-helpers/releases/download/v0.6.4/docker-credential-pass-v0.6.4-amd64.tar.gz
    dest: /tmp/
    mode: '0755'

- name: Install docker-credential-pass
  ansible.builtin.unarchive:
    src: /tmp/docker-credential-pass-v0.6.4-amd64.tar.gz
    dest: /usr/local/bin/
    mode: '0755'
    remote_src: true

- name: Create docker config folder
  ansible.builtin.file:
    path: ~/.docker
    state: directory
    mode: '0700'
  become_user: '{{ developer }}'

- name: Copy Docker config
  ansible.builtin.copy:
    src: config.json
    dest: ~/.docker/
    mode: '0600'
  become_user: '{{ developer }}'

- name: Initialize password store
  ansible.builtin.command:
    cmd: /usr/bin/pass init alkurbatov@umbrella.org
    creates: ~/.password-store
  become_user: '{{ developer }}'
