---

  - name: Install additional software for work
    dnf:
      state: present
      name: [
        'ant',
        'java-11-openjdk',
        'ruby'
      ]

  - name: Download Sencha installer
    get_url:
      url: http://cdn.sencha.com/cmd/6.7.0.63/no-jre/SenchaCmd-6.7.0.63-linux-amd64.sh.zip
      dest: /root/work/tmp
      mode: '0440'

  - name: Extract SenchaCmd into /root/work/tmp
    unarchive:
      src: /root/work/tmp/SenchaCmd-6.7.0.63-linux-amd64.sh.zip
      dest: /root/work/tmp
      remote_src: yes

  - name: Open admin panel port
    firewalld:
      port: 8888/tcp
      permanent: yes
      state: enabled
      immediate: yes

  - name: Copy application config
    copy:
      src: extjsdev.setup/files/pstorage-ui.conf
      dest: /etc/nginx/sites-available/
      owner: root
      group: root
      mode: '0644'
    notify:
      - Restart nginx

  - name: Enable application config
    file:
      src: /etc/nginx/sites-available/pstorage-ui.conf
      dest: /etc/nginx/sites-enabled/pstorage-ui.conf
      owner: root
      group: root
      state: link
    notify:
      - Restart nginx
