---

  - name: Install additional software from Fedora repos
    dnf:
      state: present
      name: [
        cmake,
        cppcheck,
        gdb,
        libasan,
        libstdc++-static,
        mathjax,
        python3-aiofiles,
        python3-aiohttp,
        python3-flake8,
        python3-matplotlib,
        python3-nbconvert,
        python3-numpy,
        python3-pandas,
        python3-seaborn,
        python3-tqdm,
        sscg,
        unzip,
        zip,
      ]

  - name: Install additional software from pip
    pip:
      name: [
        humanize, # NB (alkurbatov): As humanize in Fedora repos is too old.
        lightgbm==2.3.1, # NB (alkurbatov): Also, brings scikit-learn.
        notebook,
      ]

  - name: Pull the Ubuntu docker image
    docker_image:
      name: ubuntu:18.04
      source: pull
      tls: yes

  - name: Create Jupyter configuration folder
    file:
      path: /root/.jupyter
      state: directory
      mode: '0700'

  - name: Copy Jupyter config
    template:
      src: mldev.setup/files/jupyter_notebook_config.json.j2
      dest: /root/.jupyter/jupyter_notebook_config.json
      owner: root
      group: root
      mode: '0644'

  - name: Generate SSL certificates
    command:
      cmd: /usr/bin/sscg
      chdir: /root/.jupyter
      creates: /root/.jupyter/service-key.pem

  - name: Create folder for the notebooks
    file:
      path: /root/work/notebooks
      state: directory
      mode: '0700'

  - name: Open Jupyter web panel access port
    firewalld:
      port: 8888/tcp
      permanent: yes
      state: enabled
      immediate: yes

  - name: Install JupyterLab
    pip:
      name: jupyterlab
    register: jupyterlab

  - name: Enable JupyterLab
    command: /usr/local/bin/jupyter serverextension enable --py jupyterlab
    when: jupyterlab.changed

  - name: Install unofficial Jupyter extensions pack
    pip:
      name: jupyter_contrib_nbextensions

  - name: Install unofficial Jupyter extensions
    pip:
      name: [
        line_profiler,
        memory_profiler,
      ]

  - name: Copy Jupyter services configs
    copy:
      src: mldev.setup/files/systemd
      dest: /usr/lib/

  - name: Enable autostart and run Jupyter
    systemd:
      name: jupyter
      enabled: yes
      state: started

  - name: Increase swap size (RAM * fraction)
    lineinfile:
      path: /lib/systemd/zram-generator.conf
      regexp: "^zram-fraction"
      line: "zram-fraction = 2.0"
      backup: no
    notify:
      -  Reboot node

  - name: Cap the swap size
    lineinfile:
      path: /lib/systemd/zram-generator.conf
      regexp: "^max-zram-size"
      line: "max-zram-size = 28672"
      backup: no
    notify:
      -  Reboot node
