---

  - name: Install additional software for work
    dnf:
      state: present
      name: [
        cmake,
        cppcheck,
        gdb,
        mathjax,
        python3-aiofiles,
        python3-aiohttp,
        python3-flake8,
        python3-notebook,
        sscg,
        unzip,
      ]

  - name: Pull the Ubuntu docker image
    docker_image:
      name: ubuntu:18.04
      source: pull
      tls: yes

  - name: Create Jupyter configuration folder
    file:
      path: /root/.jupyter
      state: directory
      mode: '0700'

  - name: Copy Jupyter config
    template:
      src: mldev.setup/files/jupyter_notebook_config.json.j2
      dest: /root/.jupyter/jupyter_notebook_config.json
      owner: root
      group: root
      mode: '0644'

  - name: Generate SSL certificates
    command:
      cmd: /usr/bin/sscg
      chdir: /root/.jupyter
      creates: /root/.jupyter/service-key.pem

  - name: Create folder for the notebooks
    file:
      path: /root/work/notebooks
      state: directory
      mode: '0700'

  - name: Open Jupyter web panel access port
    firewalld:
      port: 8888/tcp
      permanent: yes
      state: enabled
      immediate: yes

  - name: Install JupyterLab
    pip:
      name: jupyterlab
    register: jupyterlab

  - name: Enable JupyterLab
    command: /usr/local/bin/jupyter serverextension enable --py jupyterlab
    when: jupyterlab.changed

  - name: Copy Jupyter services configs
    copy:
      src: mldev.setup/files/systemd
      dest: /usr/lib/

  - name: Enable autostart and run Jupyter
    systemd:
      name: jupyter
      enabled: yes
      state: started
